### ISSUE TITLE
Remove "Sector Menu" from States and Sectors pages

### ISSUE THREAD

**Issue by mariel-delagarza** [CSIS-iLab/india-states-v2#43]
### Description
The left-hand "Sector Menu" is being replaced by the table's functionality.

### Screenshots
<img width="329" alt="Screenshot 2024-01-09 at 1 34 58 PM" src="https://github.com/CSIS-iLab/india-states-v2/assets/41589348/84cdc072-e6b7-4ca2-86bd-bd89af529d15">

### Files
This repo: 
* [_includes/table-of-contents.html](https://github.com/CSIS-iLab/india-states-v2/blob/7583909cbf21551934ed83979d5ac23eeebac7ec/_includes/table-of-contents.html)
* [_layouts/state.html](https://github.com/CSIS-iLab/india-states-v2/blob/7583909cbf21551934ed83979d5ac23eeebac7ec/_layouts/state.html)
* [_layouts/sectors-landing.html](https://github.com/CSIS-iLab/india-states-v2/blob/7583909cbf21551934ed83979d5ac23eeebac7ec/_layouts/sectors-landing.html)

### Tasks
- [ ] Remove from State pages
- [ ] Remove from Sector pages
- [ ] Remove _includes file
- [ ] Check for whether any additional functionality broke (styling will be handled as part of table)
