### ISSUE TITLE
Dynamically update table Intro Content

### ISSUE THREAD

**Issue by mariel-delagarza** [CSIS-iLab/india-states-v2#44]
### Description
In the Svelte table, `IntroContent.svelte` is for everything above the dropdowns and tabs. This is where the content for the Sector/State names, their intro paragraphs, and photos would go. This content should update depending on whether the user is viewing /states, /states/[state-name], /sectors, etc. In the Svelte tables we have done previously, this content is static so this functionality is completely new. 

### Screenshots
Below are screenshots from Figma showing how the intro content changes between different pages.

#### /sector-landing
<img width="565" alt="Screenshot 2024-01-09 at 2 19 01 PM" src="https://github.com/CSIS-iLab/india-states-v2/assets/41589348/5a885850-36cb-433b-81d3-d3794e0de61a">

#### /sector-detail
<img width="582" alt="Screenshot 2024-01-09 at 2 19 28 PM" src="https://github.com/CSIS-iLab/india-states-v2/assets/41589348/8af1a26f-f41a-4855-a60a-766877f198e8">

#### /newsletter
<img width="585" alt="Screenshot 2024-01-09 at 2 20 00 PM" src="https://github.com/CSIS-iLab/india-states-v2/assets/41589348/1b633473-79fa-42ab-a1a7-27b7e806fa07">

#### /state-detail
<img width="586" alt="Screenshot 2024-01-09 at 2 20 20 PM" src="https://github.com/CSIS-iLab/india-states-v2/assets/41589348/c8b6753e-be1d-4100-a86a-c4b2ccdea120">

### Files
Example Svelte code:
* From PONI table: [src/components/IntroContent.svelte](https://github.com/CSIS-iLab/poni-table/blob/main/src/components/IntroContent.svelte)

In this repo (to start):
* [_layouts/articles-landing.html](https://github.com/CSIS-iLab/india-states-v2/blob/7583909cbf21551934ed83979d5ac23eeebac7ec/_layouts/articles-landing.html)
* [_layouts/analysis-landing.html](https://github.com/CSIS-iLab/india-states-v2/blob/7583909cbf21551934ed83979d5ac23eeebac7ec/_layouts/analysis-landing.html)
* [_layouts/national-goals-landing.html](https://github.com/CSIS-iLab/india-states-v2/blob/7583909cbf21551934ed83979d5ac23eeebac7ec/_layouts/national-goals-landing.html)
* [_layouts/sectors-landing.html](https://github.com/CSIS-iLab/india-states-v2/blob/7583909cbf21551934ed83979d5ac23eeebac7ec/_layouts/sectors-landing.html)
*[_layouts/states-landing.html](https://github.com/CSIS-iLab/india-states-v2/blob/7583909cbf21551934ed83979d5ac23eeebac7ec/_layouts/states-landing.html)

Any files in `_includes` the layouts use will be referenced with the `include` tag, for example: `{% include footer.html %}`. Be sure to also check these files as needed.

### Tasks
Update code for the following pages
- [ ] /states
- [ ] /states/[state-name]
- [ ] /sectors/[sector-name]
- [ ] /sectors/[sector-name]/[subsectors]
- [ ] /analysis (this becomes /newsletter)
