### ISSUE TITLE
Create and wire-up Sectors cards

### ISSUE THREAD

**Issue by mariel-delagarza** [CSIS-iLab/india-states-v2#45]
### Description
The new design includes a card for each sector on the Sectors landing page. They need to be (1) created and (2) wired up to the appropriate table filters or linked to the appropriate landing pages. That is, when a user clicks on "Health", they should see the table filtered to show only content from that sector. 

### Screenshots
<img width="554" alt="Screenshot 2024-01-09 at 2 36 10 PM" src="https://github.com/CSIS-iLab/india-states-v2/assets/41589348/8b39c012-fddd-46f8-9470-ba6fccca478d">

#### Response if a user clicks on "Health" on the Sectors landing page
<img width="617" alt="Screenshot 2024-01-09 at 2 39 03 PM" src="https://github.com/CSIS-iLab/india-states-v2/assets/41589348/0374dc17-34f6-4fee-8882-8b8d67cd6153">

### Tasks
- [x] Choose and prepare a background photo for each card. This will likely be the photo used on the sector's landing page.

Create cards for
- [x] Climate Change & Energy
- [x] Finance
- [x] Health
- [x] Industrial Policy and Business
- [x] Regulations
- [x] Infrastructure and Governance
- [x] Land & Labor Laws
- [x] Water & Sanitation
